include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    unnecessary_null_checks: error
    dead_code: warning
    unused_local_variable: warning
    unused_import: warning
    prefer_const_constructors: warning
    avoid_classes_with_only_static_members: ignore

linter:
  rules:
    - avoid_print # Use logs instead
    - always_use_package_imports
    - avoid_redundant_argument_values
    - avoid_unnecessary_containers
    - prefer_final_fields
    - prefer_const_constructors
    - unnecessary_null_checks
    - avoid_empty_else
    - always_declare_return_types
    - prefer_expression_function_bodies
    - prefer_mixin
    - use_super_parameters
    - parameter_assignments
    - avoid_classes_with_only_static_members
